In [4]:
import numpy as np

# X: Features tensor, y: target tensor, learning_rate: step size, num_iterations: number of iterations
# Batch gradient descent
def gradient_descent(X, y, learning_rate, num_iterations):
  num_samples, num_features = X.shape
  # Init weight params as 0
  theta = np.zeros(num_features)
  for _ in range(num_iterations):
    # Dot X and Parameters to calculate Y_output. Take difference of Y_output and y as loss. Dot X Transpose and loss, divide by num_samples
    gradient = np.dot(X.T, (np.dot(X, theta) - y)) / num_samples
    # Update gradients in opposite direction
    theta -= learning_rate * gradient
  return theta

# X: Features tensor, y: target tensor, learning_rate: step size, num_iterations: number of iterations
def mini_batch_gradient_descent(X, y, learning_rate, num_iterations, b):
  num_samples, num_features = X.shape
  theta = np.zeros(num_features)
  for _ in range(num_iterations):
    for i in range(0, len(y), b):
      X_i = X[i:i+b]
      y_i = y[i:i+b]
      gradient = np.dot(X_i.T, (np.dot(X_i, theta) - y_i)) / num_samples
      theta -= learning_rate * gradient
  return theta

# X: Features tensor, y: target tensor, learning_rate: step size, num_iterations: number of iterations
def stochastic_gradient_descent(X, y, learning_rate, num_iterations):
  num_samples, num_features = X.shape
  theta = np.zeros(num_features)
  for _ in range(num_iterations):
    randIndex = np.random.randint(0, num_samples)
    X_i = X[randIndex, :]
    y_i = y[randIndex]
    gradient = np.dot(X_i.T, (np.dot(X_i, theta) - y_i)) / num_samples
    theta -= learning_rate * gradient
  return theta

# X = features tensor of format: (Shelf_length, quantity in stock, import distance)
# y = label of sample, given as scalar value of price of fruit
sampleX = np.array([ [1,10,10],
                     [2,7,10],
                     [3,3,10],
                     [4,2,8],
                     [1,9,8],
                     [1,12,8],
                     [2,7,21],
                     [3,10,5],
                     [2,6,5],
                     [3,6,5] ])
fruitPrices = np.array([5, 4, 6, 3, 5.8, 5, 6, 3.5, 3.5, 2])

gd_weights = gradient_descent(sampleX, fruitPrices, 0.01, 10)
mini_batch_gd_weights = mini_batch_gradient_descent(sampleX, fruitPrices, 0.01, 10, 2)
stochastic_gd_weights = stochastic_gradient_descent(sampleX, fruitPrices, 0.01, 10)

print(gd_weights)
print(np.dot(sampleX[0], gd_weights))

print(mini_batch_gd_weights)
print(np.dot(sampleX[0], mini_batch_gd_weights))

print(stochastic_gd_weights)
print(np.dot(sampleX[0], stochastic_gd_weights))

print("\n ####################################### Different Learning Rates ############################################################################## \n")

# loss = []
# plot (num_iterations, loss)
# loss = diff(y, np.dot(sampleX[0], gd_weights))
for j in range(0, 10):
  j_j = 0.005 + 0.001*j
  gd_weights = gradient_descent(sampleX, fruitPrices, j_j, 10)
  print(f"Gradient Descent for Learning Rate: {j_j} produces the resulting Weight: {gd_weights}")
  print(f"Output of first sample: {np.dot(sampleX[0], gd_weights)}")

# plt.plot(num_iterations, loss, "bo", label="Training loss")
# plt.plot(num_iterations, val_loss, "b", label="Validation loss")
# plt.title("Training and validation loss")
# plt.xlabel("Epochs")
# plt.ylabel("Loss")
# plt.legend()
# plt.show()

print("\n")

for j in range(0, 10):
  j_j = 0.005 + 0.001*j
  mini_batch_gd_weights = mini_batch_gradient_descent(sampleX, fruitPrices, j_j, 10, 2)
  print(f"Mini_Batch Gradient Descent for Learning Rate: {j_j} produces the resulting Weight: {mini_batch_gd_weights}")
  print(f"Output of first sample: {np.dot(sampleX[0], mini_batch_gd_weights)}")

print("\n")

for j in range(0, 10):
  j_j = 0.005 + 0.001*j
  stochastic_gd_weights = stochastic_gradient_descent(sampleX, fruitPrices, j_j, 10)
  print(f"Stochastic Gradient Descent for Learning Rate: {j_j} produces the resulting Weight: {stochastic_gd_weights}")
  print(f"Output of first sample: {np.dot(sampleX[0], stochastic_gd_weights)}")


print("\n ####################################### Different Num Iterations ############################################################################## \n")

for j in range(10, 20):
  gd_weights = gradient_descent(sampleX, fruitPrices, 0.01, j)
  print(f"Gradient Descent for Num_Iterations: {j} produces the resulting Weight: {gd_weights}")
  print(f"Output of first sample: {np.dot(sampleX[0], gd_weights)}")

print("\n")

for j in range(10, 20):
  mini_batch_gd_weights = mini_batch_gradient_descent(sampleX, fruitPrices, 0.01, j, 2)
  print(f"Mini-Batch Gradient Descent for Num_Iterations: {j} produces the resulting Weight: {mini_batch_gd_weights}")
  print(f"Output of first sample: {np.dot(sampleX[0], mini_batch_gd_weights)}")

print("\n")

for j in range(10, 20):
  stochastic_gd_weights = stochastic_gradient_descent(sampleX, fruitPrices, 0.01, j)
  print(f"Stochastic Gradient Descent for Num_Iterations: {j} produces the resulting Weight: {stochastic_gd_weights}")
  print(f"Output of first sample: {np.dot(sampleX[0], stochastic_gd_weights)}")






[0.08308768 0.2343672  0.26379581]
5.064717861811059
[0.08942297 0.23010172 0.23712781]
4.761718353081214
[0.06867058 0.16785013 0.25436296]
4.290801550066071

 ####################################### Different Learning Rates ############################################################################## 

Gradient Descent for Learning Rate: 0.005 produces the resulting Weight: [0.07059087 0.22680162 0.27245693]
Output of first sample: 5.063176428344221
Gradient Descent for Learning Rate: 0.006 produces the resulting Weight: [0.07318702 0.22887243 0.27041922]
Output of first sample: 5.066103514092308
Gradient Descent for Learning Rate: 0.007 produces the resulting Weight: [0.07574266 0.23066254 0.26859556]
Output of first sample: 5.068323675470176
Gradient Descent for Learning Rate: 0.008 produces the resulting Weight: [0.07825763 0.23220412 0.26696256]
Output of first sample: 5.0699244546592235
Gradient Descent for Learning Rate: 0.009000000000000001 produces the resulting Weight: [0.0